package com.flymaccin.macmaestro;
import android.app.*;import android.os.*;import android.graphics.Color;import android.widget.*;
public class MainActivity extends Activity{
 int panel=Color.rgb(24,24,31),white=Color.rgb(240,240,244),muted=Color.rgb(145,145,155),gold=Color.rgb(214,179,90),green=Color.rgb(80,200,130);String workspace="DIRECTOR";
 public void onCreate(Bundle b){super.onCreate(b);String in=StudioMesh.receive(this);show();if(in!=null)Toast.makeText(this,"Studio Mesh project received",Toast.LENGTH_SHORT).show();}
 protected void onNewIntent(android.content.Intent i){super.onNewIntent(i);setIntent(i);if(StudioMesh.receive(this)!=null){show();Toast.makeText(this,"Studio Mesh project received",Toast.LENGTH_SHORT).show();}}
 TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(18,12,18,12);return v;}
 Button b(String s){Button x=new Button(this);x.setText(s);x.setTextColor(white);x.setBackgroundColor(panel);return x;}
 void route(LinearLayout p,String label,String pkg){Button x=b("SEND TO "+label);x.setOnClickListener(v->StudioMesh.send(this,pkg,StudioMesh.bundle("Mac-Maestro",workspace)));p.addView(x);}
 void show(){ScrollView sc=new ScrollView(this);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(24,18,24,18);p.setBackgroundColor(Color.rgb(9,9,12));p.addView(t("Mac-Maestro Android",28,gold));p.addView(t("AI ENGINE · FME STUDIO MESH",12,muted));for(String s:new String[]{"DIRECTOR","IMAGE","VIDEO","MUSIC","AUDIO"}){Button x=b(s);x.setOnClickListener(v->{workspace=s;Toast.makeText(this,s+" workspace",Toast.LENGTH_SHORT).show();});p.addView(x);}p.addView(t("CONNECTED STUDIOS",14,green));route(p,"DEMONIC","com.flymaccin.demonicaistudio");route(p,"theDAW","com.flymaccin.thedaw");route(p,"GENERIC DAW","com.flymaccin.genericdaw");route(p,"MEADOWLARK","com.flymaccin.meadowlarkdemonic");route(p,"TUNEFLOW","com.flymaccin.tuneflow");Button share=b("SHARE TO ANY STUDIO");share.setOnClickListener(v->StudioMesh.share(this,StudioMesh.bundle("Mac-Maestro",workspace)));p.addView(share);p.addView(t(StudioMesh.last(this).isEmpty()?"No incoming mesh project yet.":"Incoming mesh project cached.",12,muted));sc.addView(p);setContentView(sc);}
}